#######################################generated by Mausam kumar Sinha on 01-FEB-2018#######################
#This script will helps to create different fileset(UNRESTRICTED,RESTRICTED)
#Before Execution of this script,Configure the proper value in  users.cfg file

#!/usr/bin/python
import os
import commands

from ConfigParser import SafeConfigParser


def getconfig(option):
    parser = SafeConfigParser()
    parser.read("../users.cfg")
    value = parser.get('SEC', option)
    return value


def delete_fileset(fileset):
    stop_fileset = '''gtacl -s -c "scf;assume \$zpmon;stop fileset ''' + fileset + '''" '''
    ptf = commands.getstatusoutput(stop_fileset)
    print(ptf)
    print("deleting fileset",fileset)
    cmd = '''gtacl -s -c "scf;assume \$zpmon;delete fileset ''' + fileset + '''"'''
    print(cmd)
    commands.getstatusoutput(cmd)
	
def startFileset(fileset):
    print("starting the fileset",fileset,"after newly creation")
    cmd = '''gtacl -s -c "scf;assume \$zpmon;start fileset ''' + fileset + '''"'''
    print(cmd)
    output = commands.getstatusoutput(cmd)
    print(output)
	

def createUnrestrictedFileset(fileset, mount):
    cmd = '''gtacl -s -c "scf assume \$ZPMON; add fileset ''' + fileset + ''',pool rootpool,catalog \$oss,MNTPOINT \\\"''' + mount + '''\\\" "'''
   # cmd += ''',mntpoint \\"''' + mount + ''' \\"" '''
    print(cmd)
    output=commands.getstatusoutput(cmd)
    print(output)
    startFileset(fileset)



def createRestrictedFileset(fileset, mount):
    cmd = '''su - super.spa1,welcome -c "gtacl -s -c 'scf assume \$ZPMON; add fileset R4,pool rootpool,catalog \$oss,RESTRICTEDACCESS ENABLED,MNTPOINT \\\"/rest_v4\\\" ' "'''
    print(cmd)
    #su_cmd = '''su - super.spa1,welcome -c "''' + cmd + '''"'''
    #print(su_cmd)
    output=commands.getstatusoutput(cmd)
    print(output)
    startFileset(fileset)


def main():
    un_fileset = getconfig("UNRESTRICTED")
    print(un_fileset)
    un_fileset_list = un_fileset.split(",")
    for i in un_fileset_list:
        fileset = i.split(":")[0]
        mount = i.split(":")[1]
        if not os.path.exists(mount):
            os.mkdir(mount)
        print("===============================delete UnRestrictedFileset called=======================================")
        delete_fileset(fileset)
        print("===============================createUnRestrictedFileset fileset called=======================================")
        createUnrestrictedFileset(fileset, mount)
        print(fileset)
        print(mount)

    re_fileset = getconfig("RESTRICTED")
    print(re_fileset)
    re_fileset_list = re_fileset.split(",")
    for i in re_fileset_list:
        fileset = i.split(":")[0]
        mount = i.split(":")[1]
        if not os.path.exists(mount):
            os.mkdir(mount)
	print("===============================delete RestrictedFileset called=======================================")
    delete_fileset(fileset)
    print("===============================createRestrictedFileset fileset called=======================================")
    createRestrictedFileset(fileset, mount)
    print(fileset)
    print(mount)


if __name__ == "__main__": main()

